# Generated by Django 5.0.4 on 2024-04-23 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('frais_gestion', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('civilite', models.CharField(choices=[('M', 'Monsieur'), ('Mme', 'Madame')], default='M', max_length=4)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=50)),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='copal_manager.contrat')),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('qte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_presta', models.CharField(max_length=10)),
                ('prix_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_facture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='copal_manager.facture')),
            ],
        ),
        migrations.AddField(
            model_name='contrat',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copal_manager.proprietaire'),
        ),
        migrations.CreateModel(
            name='BienImmobilier',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=50)),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=20)),
                ('taille', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_bien', models.CharField(max_length=50)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='copal_manager.contrat')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='copal_manager.proprietaire')),
            ],
        ),
    ]
