# Generated by Django 5.0.4 on 2024-05-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienimmobilier',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='copal_manager.contrat'),
        ),
        migrations.AlterField(
            model_name='bienimmobilier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bienimmobilier',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='copal_manager.proprietaire'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='copal_manager.contrat'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
