# Generated by Django 5.0.4 on 2024-05-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0002_alter_bienimmobilier_contrat_alter_bienimmobilier_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='civilite',
            field=models.CharField(choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('M&Mme', 'Monsieur et Madame')], default='M', max_length=20),
        ),
    ]
