# Generated by Django 5.0.4 on 2024-10-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0003_alter_proprietaire_civilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='numero_contrat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
