# Generated by Django 5.0.4 on 2024-10-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0004_contrat_numero_contrat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='numero_contrat',
        ),
    ]
