# Generated by Django 5.0.4 on 2024-10-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0006_contrat_numero_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='numero_contrat',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
