# Generated by Django 5.0.4 on 2024-10-14 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0007_alter_contrat_numero_contrat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bienimmobilier',
            name='contrat',
        ),
        migrations.AddField(
            model_name='contrat',
            name='bien_immo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='copal_manager.bienimmobilier'),
            preserve_default=False,
        ),
    ]
