# Generated by Django 5.0.4 on 2024-11-03 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0008_remove_bienimmobilier_contrat_contrat_bien_immo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='frais_mer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bienimmobilier',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copal_manager.proprietaire'),
        ),
    ]
