# Generated by Django 5.0.4 on 2024-11-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0009_contrat_frais_mer_alter_bienimmobilier_proprietaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bienimmobilier',
            old_name='taille',
            new_name='surface',
        ),
    ]
