# Generated by Django 5.0.4 on 2024-11-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0010_rename_taille_bienimmobilier_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienimmobilier',
            name='etage',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='bienimmobilier',
            name='nb_chambres',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='bienimmobilier',
            name='nb_pieces',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='bienimmobilier',
            name='nb_sdb',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
