# Generated by Django 5.0.4 on 2024-11-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0011_bienimmobilier_etage_bienimmobilier_nb_chambres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienimmobilier',
            name='commentaire',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='bienimmobilier',
            name='etage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bienimmobilier',
            name='nb_chambres',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bienimmobilier',
            name='nb_pieces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bienimmobilier',
            name='nb_sdb',
            field=models.IntegerField(default=0),
        ),
    ]
