# Generated by Django 5.0.4 on 2024-11-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0012_bienimmobilier_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienimmobilier',
            name='commentaire',
            field=models.CharField(default='Aucun', max_length=150),
        ),
    ]
