# Generated by Django 5.0.4 on 2024-12-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0013_alter_bienimmobilier_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='siret',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='civilite',
            field=models.CharField(choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('M&Mme', 'Monsieur et Madame'), ('Soc', 'Societe')], default='M', max_length=20),
        ),
    ]
