# Generated by Django 5.0.4 on 2024-12-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0014_proprietaire_siret_alter_proprietaire_civilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='siret',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
