# Generated by Django 5.0.4 on 2024-12-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0015_alter_proprietaire_siret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienimmobilier',
            name='commentaire',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
