# Generated by Django 5.0.4 on 2025-01-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0017_alter_proprietaire_civilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienimmobilier',
            name='ville',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='ville',
            field=models.CharField(max_length=50),
        ),
    ]
