# Generated by Django 5.0.4 on 2025-01-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0018_alter_bienimmobilier_ville_alter_proprietaire_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienimmobilier',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
